---
title: "A3: Incarceration"
output: html_document
---

### Introduction

In this world, there are now many incidents that includes race like how for example, Black people getting arrested for doing nothing. The variables that i mentioned and calculate is regarding the difference races that are put into jail. Whether, it's Black, White, Asian, latin, and native, I'm trying to see the difference between them in 2017 and compare the numbers between this races. 

### Summary Information

I have obtained that the average value for all of the races in 2017 with their highest and lowest value and also how much does it change over 3 years. Which, I would be only descibring the Black and White race because I use those values on my chart. The average for Black would 2543.683 and White is 486.5253. The highest and lowest value for Black would be 181333.3 and 0. Whereas, the White is 66234.2 and 0.

### The Dataset

The one who collected the data are the U.S Department of Justice Bureau of Justice Statistics The BJS census of jails, The Death in Custody Reporting Program, and the Annual Survey of Jails. The data was collected by getting the data from the help of the government that has the record of the jail intakes and custody. The data was collected to inform the public debate on mass incarceration and help guide change by providing easily accessible information on the number of people in jails and prisons for every county in the United States. There are 91.031 rows in the data and 23 columns in the data. Of course there would be question like why does this specific race has more numbers than the others and why does this has lower number compare to the others, with that there would rise a problem like racism or inequality towards some of the race. The possible limitations would be there isn't any reason on why are there getting into jail for in each of the data, I believe that if we know the reason it would be easier to compare between the races. 


### Trends Over Time Chart

{r, echo = FALSE, code = readLines("first_chart.R")}
This chart is included to show the number of Black people that were in jail though out the years. In the chart, it's shown that in the end of 1900s, there were a lot of Black people that were in jail with unknown reason it's recorded as the highest surpassing 200.000 individuals. This is also recorded in the top 5 counties, where the most highest Black people that were recorded in jail. 

### Variable Comparison Chart

{r, echo = FALSE, code = readLines("Second_chart.R")}
In this chart, there would be a comparison or relationship between Black and White people that are in jail. From the chart, it's shown that there many more Black in jail compare to Whites because there is comparison in the bottom where White is a little over 0, but for the Black it could surpass 100.000 people easily there are multiple occasions on that is happening. Whereas, the White has more than 40.000 compare to Black with 0 people in jail, there is a huge difference between those variables and circumstance. 
### Map

{r, echo = FALSE, code = readLines("Third_chart.R")}
In this last chart, in the west coast, the jail jurisdiction area is far more bigger compare to east coast where it's relatively smaller in size compare to the west coast jail for the Black people. from this graph, we can conclude that the east has far more Black people jail occupants than the west coast considering there is a lot more area to cover because there many jail covering each state and county. 
